# Generated by Django 6.0.5 on 2026-05-29 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('suburb', models.CharField(help_text='e.g., Pinetown, Westville', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterFaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short description of the issue', max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('street_address', models.CharField(blank=True, max_length=250, null=True)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='fault_images/')),
                ('severity', models.CharField(choices=[('LOW', 'Low - Minor drip or puddle'), ('MED', 'Medium - Steady leak'), ('HIGH', 'High - Burst pipe / Flooding')], default='LOW', max_length=4)),
                ('date_reported', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.residentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('DISPATCHED', 'Team Dispatched'), ('IN_PROGRESS', 'Work in Progress'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=15)),
                ('assigned_team', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='reports.waterfaultreport')),
            ],
        ),
    ]
